.build.yml: Add CMake support.

diff --git a/.build.yml b/.build.yml
--- a/.build.yml
+++ b/.build.yml
@@ -75,9 +75,17 @@ build_scripts:
   -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
   -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
   - fi
-
-  - NOCONFIGURE=1 ./autogen.sh
-  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc --enable-compile-warnings=maximum
+  -
+  - if [ -e ./autogen.sh ]; then
+  -     NOCONFIGURE=1 ./autogen.sh
+  -     scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc --enable-compile-warnings=maximum
+  - elif [ -e ./CMakeLists.txt ]; then
+  -     scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON
+  - else
+  -     echo "ERROR: Build system not supported (supported are: autogen.sh, CMake)"
+  -     exit 1
+  - fi
+  -
   - if [ $CPU_COUNT -gt 1 ]; then
   -     if [ ${DISTRO_NAME} == "debian" ];then
   -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
